name: "Companion | Powering the Streamdecks of the BEGA"
description: "Bihhhhhtfocus Companion"
version: "20.1.6"
slug: "companion"

startup: services
boot: auto

arch:
  - amd64
  - aarch64

host_network: true

webui: "http://[HOST]:8000"