name: "Companion Regie Streamdeck"
description: "Einmal Big Doener Sauce scharf"
version: "20.1.6"
slug: "companion_regie"
init: false
startup: services
boot: auto
arch:
  - amd64
  - aarch64
host_network: true
webui: "http://[HOST]:[PORT:8000]"